### ISSUE TITLE
Update melpa-stable release

### ISSUE THREAD

**Issue by sheijk** [emacs-helm/helm-descbinds#10]
The latest version on melpa-stable (and melpa) is 1.07.1. Also it's mislabelled as 1.7.1 Could you update that version to 1.08 for those of us who are wary of marmelade packages, please?

(I'm assuming the melpa package has been added by you. Let me know if this issue should be filed against melpa instead).

**Comment by cilia** [comment]
+1. Also hoping to get the package via `melba-stable` here.

**Comment by michael-heerdegen** [comment]
Thanks for reporting, I'm sorry that nobody answered yet.  I guess the package is a bit abandoned by now.

I don't use Melpa stable.  What has to be done to do that?  Or could even someone of you do it?  Feel free to do it, you have my authorization, I would be thankful.

**Comment by cilia** [comment]
I have not done this myself, but apparently if there is already a `melpa` recipe for the package, then uploading to `melpa-stable` only requires tagging a release in Git. `melpa-stable` is then supposed to automatically build the package using the tag.

See: https://github.com/milkypostman/melpa#stable-packages

**Comment by michael-heerdegen** [comment]
cilia <notifications@github.com> writes:

> See: https://github.com/milkypostman/melpa#stable-packages

Thanks.

And I guess it was Melpa that collapsed the version from 1.07.1 to
1.7.1.  Doesn't seem to be much a problem, but I guess we should try to
avoid such leading zeros.

Then we need a commit to attach the 1.08 tag to.  Would 5d8e84e be ok?  I
hope there will be more releases to Melpa stable not so far in the future.

**Comment by michael-heerdegen** [comment]
I've attached a tag to https://github.com/emacs-helm/helm-descbinds/commit/5d8e84e6c047ce8a042fdcd827abb421f4848ac7 now.  Please tell me if it work (never have done that before), @sheijk and @cilia.

I've also bumped the current version to 1.9 (not 1.09).

**Comment by cilia** [comment]
@michael-heerdegen Yes, the tagged 1.08/1.8 version is now available on `melpa-stable`. Thanks.

**Comment by michael-heerdegen** [comment]
Great.  Thanks for your hints, @cilia.
