### ISSUE TITLE
would be great to make `C-h b` work in helm buffers

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm-descbinds#12]
I am getting `helm: Error: Trying to run helm within a running helm session` whenever I try `C-h b` from some helm buffer.

**Comment by xuchunyang** [comment]
Sounds reasonable request since helm has too many key bindings (actually, each helm source can have its own keymap). Does anyone know if this can be implemented?

**Comment by michael-heerdegen** [comment]
Has this problem been fixed by the commit from @xuchunyang , @vspinu ?

**Comment by vspinu** [comment]
Yes. I can confirm that the problem is not there. Big thanks!
