### ISSUE TITLE
Startup error: Symbol's function definition is void: helm-descbinds-mode

### ISSUE THREAD

**Issue by cilia** [emacs-helm/helm-descbinds#16]
Hi, just installed the package, and edit the `Emacs` config, but getting the error message above.

Doing `--debug-init` gives the following:

    Debugger entered--Lisp error: (void-function helm-descbinds-mode)
    (helm-descbinds-mode)
    eval-buffer(#<buffer  *load*> nil "/Users/cilia/.emacs" nil t)  ; Reading at buffer position 2821
    load-with-code-conversion("/Users/cilia/.emacs" "/Users/cilia/.emacs" t t)
    load("~/.emacs" t t)
    #[0 "^H\205\262^@   \306=\203^Q^@\307^H\310Q\202;^@\311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\$ ...
    command-line()
    normal-top-level()

I installed `helm-descbinds` from `melpa-stable`, which I am not sure if it is up-to-update. Any idea how to fix the problem is much appreciated.

**Comment by michael-heerdegen** [comment]
The first standard question in such a situation is whether you have
```
(package-initialize)
```
in your config, which is mandatory.

**Comment by cilia** [comment]
Yes, I do have it, at the top section of my `.emacs`. I've tried manually compiling and installing `helm-descbinds`, and loaded the package manually with `(require 'helm-descbinds)` and that worked fine.

Anything else I can check?

**Comment by cilia** [comment]
Related, I see in the README that, both of the following are required in the config for `helm-descbinds` to work:

    (require 'helm-descbinds)
    (helm-descbinds-mode)

But my understanding is that, if the package is installed using the package manager (from MELPA or MELPA-stable), then we don't need to have `(require 'helm-descbinds)` in the config?

**Comment by michael-heerdegen** [comment]
The package at Melpa stable is not up-to-date, see https://github.com/emacs-helm/helm-descbinds/issues/10, but I hope it will be very soon.

My version (I use the repository repo) has an autoload cookie before the definition of `helm-descbinds-mode`.  Does your version have it?  If not: that's the problem.  If it has, I don't understand what's going on.

The code of helm-descbinds clearly needs some love, and maybe a new maintainer, too.

**Comment by michael-heerdegen** [comment]
Does the problem persist with the new version at Melpa stable, @cilia?

**Comment by michael-heerdegen** [comment]
Please reopen if you still see the problem, thanks.

**Comment by KraevRoot** [comment]
go to the .emacs.d/elpa folder and remove all helm folders and restart/start emacs.
