### ISSUE TITLE
Please release the latest version 1.12 on MELPA stable

### ISSUE THREAD

**Issue by sixpointzero** [emacs-helm/helm-descbinds#21]
helm-descbinds hasn't had a release on [MELPA stable](https://stable.melpa.org/#/helm-descbinds) since the past two years. Please consider releasing the latest version of helm-descbinds on MELPA stable.

**Comment by michael-heerdegen** [comment]
Not releasing was not intended, sorry.

Do I have to push tags separately with Git (Magit) ?  If yes, I've done so now; if not, I don't know what's wrong, please reopen in this case.

Thanks for reporting!

**Comment by michael-heerdegen** [comment]
According to https://stable.melpa.org/ version 1.12 should be available now.

**Comment by sixpointzero** [comment]
Thanks! It's up on https://stable.melpa.org/ now.
