### ISSUE TITLE
Unusual matching behaviour

### ISSUE THREAD

**Issue by cruegge** [emacs-helm/helm-descbinds#23]
Matching in helm-descbinds is unusual for helm plugins in that the input string is not split into words which are then matched individually. Only regexps work.

I do not really understand the way helm's API works, but for me, redefining `helm-descbinds-source` to use `helm-build-sync-source` instead of just returning an alist fixed the problem. Here's my redefinition:

```elisp
(defun helm-descbinds-source (name candidates)
  (append (helm-build-sync-source name
            :candidates candidates)
          helm-descbinds-source-template))
```

**Comment by thierryvolpiatto** [comment]
Christoph Ruegge <notifications@github.com> writes:

> Matching in helm-descbinds is unusual for helm plugins in that the
> input string is not split into words which are then matched
> individually. Only regexps work.
>
> I do not really understand the way helm's API works, but for me,
> redefining helm-descbinds-source to use helm-build-sync-source instead
> of just returning an alist fixed the problem. Here's my redefinition:
>
> (defun helm-descbinds-source (name candidates)
>   (append (helm-build-sync-source name
>             :candidates candidates)
>           helm-descbinds-source-template))

Your fix is right, could you provide a PR?

Thanks.

-- 
Thierry
