### ISSUE TITLE
Byte compile

### ISSUE THREAD

**Issue by cloudchin** [emacs-helm/helm-descbinds#34]
Hi - Sorry this is somewhat general but how would I do this for this package?

I have helm installed from source using your makefile, which byte compiles the corresponding .el files before `make install`. Since this isn't packaged with it, I've got to byte compile it myself.

I tried adapting the compile language of some emacs package Makefiles, I ran

`emacs -Q -batch -L . -f batch-byte-compile helm-descbinds.el` from inside the cloned repo and get

`helm-descbinds.el:73:2: Error: Cannot open load file: No such file or directory, helm`

I then cp'd the .el file into my site-lisp/helm directory, tried again, and got
`helm-descbinds.el:73:2: Error: Cannot open load file: No such file or directory, async`

I do have emacs-async installed in its own site-lisp directory and it and helm are currently installed and working.

**Comment by thierryvolpiatto** [comment]
cloudchin ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Hi - Sorry this is somewhat general but how would I do this for this package?

Try to use async-byte-compile-file to compile such extensions, otherwise
you have to modify the make file so that it is aware of the async (and
other deps).

> I have helm installed from source using your makefile, which byte compiles the corresponding .el files before make install. Since this isn't packaged with it, I've got to byte compile it
> myself.
>
> I tried adapting the compile language of some emacs package Makefiles, I ran
>
> emacs -Q -batch -L . -f batch-byte-compile helm-descbinds.el from inside the cloned repo and get

Try emacs -q -batch -L . -f batch-byte-compile helm-descbinds.el instead

assuming Helm has been installed with "make install", it is what the
Helm make file does (see comment in it).

> helm-descbinds.el:73:2: Error: Cannot open load file: No such file or directory, helm
>
> I then cp'd the .el file into my site-lisp/helm directory, tried again, and got
> helm-descbinds.el:73:2: Error: Cannot open load file: No such file or directory, async

No, you should not run make in such directory.

-- 
Thierry

**Comment by cloudchin** [comment]
`emacs -q -batch -L . -f batch-byte-compile helm-descbinds.el` worked! Thank you very much.
