### ISSUE TITLE
C-c h: Wrong type argument: commandp, (message (helm-alive-p))

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm-descbinds#6]
I just installed helm-descbinds through the Emacs package manager (version `Version: 20130326.1442`). I am using the latest stable version of Emacs (24.3) and the latest version of Helm in the Emacs package manager (i.e. `Version: 20130329.1612`).

I added the following to my `.emacs` file after the code that loads Helm

``` elisp
(require 'helm-descbinds)
(helm-descbinds-mode)
```

When I do `C-c h` I get the following error:
`Wrong type argument: commandp, (message (helm-alive-p))`

**Comment by michael-heerdegen** [comment]
Without feedback, I can't do anything.  Please reopen if you still see it.  Thanks.
