### ISSUE TITLE
First sentence of command help for searching would be very useful.

### ISSUE THREAD

**Issue by lewang** [emacs-helm/helm-descbinds#9]

**Comment by michael-heerdegen** [comment]
What help do you mean?  PR welcome, if you have the time.  Thanks.

**Comment by michael-heerdegen** [comment]
@lewang It's ok when you don't want to make a PR, but please tell me what "first sentence" that seemingly doesn't exist you mean.

**Comment by michael-heerdegen** [comment]
I improved the documentation in the header as well as for the command.  Hope that includes what you had asked for.  Thanks.
